//
// Generated file, do not edit! Created by opp_msgc 4.2 from sources/PcnAccidentMsg.msg.
//

#ifndef _PCNACCIDENTMSG_M_H_
#define _PCNACCIDENTMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "PcnMsg_m.h"
#include <string>
// }}



/**
 * Class generated from <tt>sources/PcnAccidentMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet PcnAccidentMsg extends PcnMsg {
 *     string accidentStatus;     
 *     int pcnMsgID;
 *         
 * }
 * </pre>
 */
class PcnAccidentMsg : public ::PcnMsg
{
  protected:
    opp_string accidentStatus_var;
    int pcnMsgID_var;

  private:
    void copy(const PcnAccidentMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PcnAccidentMsg&);

  public:
    PcnAccidentMsg(const char *name=NULL, int kind=0);
    PcnAccidentMsg(const PcnAccidentMsg& other);
    virtual ~PcnAccidentMsg();
    PcnAccidentMsg& operator=(const PcnAccidentMsg& other);
    virtual PcnAccidentMsg *dup() const {return new PcnAccidentMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getAccidentStatus() const;
    virtual void setAccidentStatus(const char * accidentStatus);
    virtual int getPcnMsgID() const;
    virtual void setPcnMsgID(int pcnMsgID);
};

inline void doPacking(cCommBuffer *b, PcnAccidentMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PcnAccidentMsg& obj) {obj.parsimUnpack(b);}


#endif // _PCNACCIDENTMSG_M_H_
