//
// Generated file, do not edit! Created by opp_msgc 4.2 from sources/PcnInitialMsg.msg.
//

#ifndef _PCNINITIALMSG_M_H_
#define _PCNINITIALMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "PcnMsg_m.h"
// }}



/**
 * Class generated from <tt>sources/PcnInitialMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet PcnInitialMsg extends PcnMsg {
 *     double appZone;  
 * }
 * </pre>
 */
class PcnInitialMsg : public ::PcnMsg
{
  protected:
    double appZone_var;

  private:
    void copy(const PcnInitialMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PcnInitialMsg&);

  public:
    PcnInitialMsg(const char *name=NULL, int kind=0);
    PcnInitialMsg(const PcnInitialMsg& other);
    virtual ~PcnInitialMsg();
    PcnInitialMsg& operator=(const PcnInitialMsg& other);
    virtual PcnInitialMsg *dup() const {return new PcnInitialMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getAppZone() const;
    virtual void setAppZone(double appZone);
};

inline void doPacking(cCommBuffer *b, PcnInitialMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PcnInitialMsg& obj) {obj.parsimUnpack(b);}


#endif // _PCNINITIALMSG_M_H_
